version: '3.1'

services:

  db:
    image: postgres
    restart: always
    # container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: recipes_db
    ports:
      - "5432:5432"